### ISSUE TITLE
Garbage-collected memory buffer

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAdrv.jl#57]
Instead of the current `CuArray`, which is going to be superseded by the [CuArrays](https://github.com/MikeInnes/CuArrays.jl) package, we should have a more generic buffer type to manage memory. This would remove some significant complexity from CUDAdrv, which isn't part of the driver API so doesn't belong there. It would also allow to hide the `OwnedPtr` interface better.

wrt. freeing memory, as GC support isn't going to happen soon, we could make it easier to free known out-of-scope memory using an idempotent `delete` call which tags the buffer as freed (ie. setting a flag or wiping the pointer, if we maintain a single reference), so that a finalizer later on doesn't clash with this interface. Making this API asynchronous would probably also solve some performance issues. This is better then calling `finalize` which is apparently very expensive.

**Comment by yuyichao** [comment]
FWIW, I don't think there's any need for GC support. You should just call GC if allocation fails.

**Comment by maleadt** [comment]
> You should just call GC if allocation fails.

~~What do you mean exactly?
I probably should have elaborated this braindump a little more; I was thinking about a way to have GPU buffers freed eagerly as that's apparently a big problem with users of GPU array packages. After discussing with @vtjnash, artificially increasing memory pressure didn't seem like a good solution (although it still seems like the preferred solution due to no extra syntax required), and deterministic destruction also doesn't seem to be around the corner.~~

OK I get it.

**Comment by yuyichao** [comment]
I just mean https://github.com/inducer/pyopencl/blob/2d0c97911345ce96c29d37bb0f609cf9b2878351/src/c_wrapper/error.h#L316

You shouldn't increase the actual memory pressure only the GPU memory pressure and I don't see a need to let the GC maintain that pressure since your code has to tell the GC about it anyway. It also shouldn't be checked during normal allocation and only during your allocations so it'll just be a number that you'll update and check in your code and so it might as well be all part of your code. (The GC really doesn't need to know about it and won't use it in any way....). Given this, you can even just use the driver to maintain that pressure by detecting allocation failure. If you want to be more fancy with multiple process you can of course maintain an allocation count yourself and trigger a GC early. It's entirely up to you what the GC heuristic you want to have. The only thing the GC will do is to free dead objects when you think it should do it.

**Comment by maleadt** [comment]
Yeah, that's a good idea actually. @MikeInnes mentions that `gc()` does not necessarily do a full sweep, any comments on that?

One problem with just doing a collect-on-failure is that we could consume all of the GPU's memory while we actually would want to manage it a little more carefully. But I guess we could just keep track of pressure at the GPU alloc / GPU free interface, and call `gc()` a little more eagerly to keep usage within limits.

**Comment by yuyichao** [comment]
`gc(false)` doesn't, and that's what you should call first if it didn't free enough you can call `gc()` and do a full mark-sweep. This is indeed the only part of the GC heuristic (when to do full collection) that can't currently be done in user code. I'm not sure how it can be exposed actually though the method mentioned above should work in the mean time and only be slightly slower in the worse case.

> One problem with just doing a collect-on-failure is that we could consume all of the GPU's memory while we actually would want to manage it a little more carefully.

Right, that's why I said if you want to support other processes you'll need to keep your own counter.

> But I guess we could just keep track of pressure at the GPU alloc / GPU free interface, and call gc() a little more eagerly to keep usage within limits.

Right. And no matter what GC support you want to have this is always necessary. The GC is not going to automatically get notified when you allocate GPU memory.

**Comment by maleadt** [comment]
Implemented in CuArrays.
