### ISSUE TITLE
Support for older GPUs

### ISSUE THREAD

**Issue by karajan9** [JuliaGPU/CUDAdrv.jl#97]
First of all, I am by no means an expert on the Julia-CUDA-ecosystem, so I hope I came to the right place.

I have a laptop that is a few years old and has a GT 555M graphics card, which supports CUDA. Unfortunately only version 2.1 which apparently isn't supported by CUDAdrv (at least I get an error saying so).

Is there any chance support for graphic cards like mine would be added in the future?

**Comment by maleadt** [comment]
> which apparently isn't supported by CUDAdrv (at least I get an error saying so)

I assume this isn't a CUDAdrv error, but an error when building CUDAnative? Could you list the exact error?

Anyway, `sm_21` devices are still supported, but only by CUDA < 8.0 (see https://github.com/JuliaGPU/CUDAapi.jl/blob/4d0c0b46ae297c1128f89b123c9be4a3a47ba259/src/compatibility.jl#L64-L87). Which version of CUDA are you using?

**Comment by karajan9** [comment]
First of all, thank you for your quick and kind response!

I hope this is CUDA <= 8.0, because that's the version I have (after failing with 9.1 :-D)
`nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
`

Judging by my google searches, the message I got was "Device capability v2.1.0 not supported by available toolchain". This was after I had sucessfully built the packages and tried to execute a @ cuda command taken from a tutorial.

However ...

At the moment I am unable to reproduce my own errors, because it seems my graphics card may have died on me at the first chance it got after the old gaming days. The nvidia drivers don't seem to do anything, which is no big surprises, as lspci fails to list the device entirely.
Oh well... If I manage to sort this out, I will come back to you, hopefully with a little more information.

**Comment by maleadt** [comment]
> I hope this is CUDA <= 8.0, because that's the version I have (after failing with 9.1 :-D)

Yes, you're right, I misinterpreted my own code. Those version ranges are inclusive (but have previously been exclusive, in my defense).

>  Oh well... If I manage to sort this out, I will come back to you, hopefully with a little more information.

Great. In the meantime, I'll leave this open until I've made the error messages more descriptive (eg. `your CUDA doesn't support` instead of a generic `your toolchain doesn't support`).

**Comment by karajan9** [comment]
Okay, thanks!

Hm... not sure if I understood you correctly, but in theory my device should have been supported with my CUDA 8.0, right? So I'm not sure if this is just a problem with the labeling.

But I seem to be a dead end, I'm not sure how much is won by putting too much effort into this ;-)

**Comment by maleadt** [comment]
Sorry, forgot about your comment. Did you get it working? Because CUDA 8.0 should definitely be supported in combination with your device.

I've added some additional logging in https://github.com/JuliaGPU/CUDAnative.jl/commit/9f6659f22f696471b7aeee780ecb942c73cb178c#diff-44f85496bf6930d196d5904271343563, so if it still doesn't work please run with `TRACE=1` from CUDAnative/CUDAapi master branches.

**Comment by maleadt** [comment]
I think you were using CUDA 8.0, but with a more recent driver. Although apparently that shouldn't be an issue. https://github.com/JuliaGPU/CUDAnative.jl/issues/165
